spring:
  application:
    name: bitfrost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:h2:file:./data/mydb
    driverClassName: org.h2.Driver
    username: sa
    password: password
app:
  past-date-range: 7
  max-retry-timeout: 3600
  cors:
    allowed-origins:
      - http://localhost:5173
      - https://bitfrost.sau-portal.de
  jwt:
    key-id: bitfrost-key
    issuer-uri: http://localhost:8080
    keys:
      public: file:./public_key.pem
      private: file:./private_key.pem
    identity:
      duration: 36000000 # 10 hours
    refresh:
      duration: 2678400000 # 1 month
    executor:
      duration: 3600000 # 1 hour
management:
  endpoints:
    web:
      exposure:
        include: health,readiness,liveness,prometheus
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
