spring:
  application:
    name: bitfrost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
app:
  jwt:
    secret: aa7b0e9187c3eec1bb5da2297b87c0ad6d8cb71188efea3c5b2d5bd189e5e397
