name: CI - Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '21', '22' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Temurin JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Show Java and Maven versions
        run: |
          java -version
          mvn -v

      - name: Build and run tests
        run: mvn -B -ntp clean verify

      - name: Upload test reports (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-java-${{ matrix.java }}
          path: |
            **/target/surefire-reports/**
          if-no-files-found: ignore
          retention-days: 14

      - name: Upload integration test reports (Failsafe)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failsafe-reports-java-${{ matrix.java }}
          path: |
            **/target/failsafe-reports/**
          if-no-files-found: ignore
          retention-days: 14
